config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  get 'boards' => 'boards#index'
  get '/boards/:id'=> 'boards#show', as: :board
  get '/topicks/:id' => 'topicks#index', as: :topick
  get 'boards/newBoard' => 'boards#newBoard'
  get 'boards/:id/newTopick' => 'topicks#newTopick'
  get '/register' => 'users#new'
  resources :users
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :topicks
  has_many :posts
  validates :name, presence: true, uniqueness: true
  validates :topick_id, uniqueness: true, allow_blank: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user, counter_cache: true
	belongs_to :topick, counter_cache: true
  belongs_to :board, counter_cache: true
  validates :message, presence: true
  validates :user_id, presence: true
  validates :topick_id, presence: true
	validates :board_id, presence: true
end

app/models/topick.rb
class Topick < ActiveRecord::Base
	has_many :posts
	belongs_to :user
	belongs_to :board, counter_cache: true
  validates :theme, presence: true
  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :topicks
  has_many :posts
  validates :handle, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /@/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
    @boards = Board.all
    @users = User.all
  end
  def newBoard
    board = Board.create name, topick_id
    @boards << board
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
    @users = User.all
  end
  def show
    @board = Board.find(params[:id])
    @topicks = @board.topicks.all
  end
  def newBoard
    board = Board.create name, topick_id
    @boards << board
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/topicks_controller.rb
class TopicksController < ApplicationController
  def index
    @topick = Topick.find(params[:id])
    @posts = @topick.posts.all    
  end
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:handle, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topicks_helper.rb
module TopicksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/board/index.html.erb
<%= stylesheet_link_tag "main.scss" %>
<div id = "wrapper">
  <div id = "header">
    <%= link_to "Login" %>
    <%= link_to "Register" %>
  </div>
  <div id = "table_wrapper">
    <p><%= link_to "Create new board", 
      controller: "board",
      action: "newBoard"%></p>
    <table id = "boards">
      <% @boards.each do |board| %>
        <tr>  
          <td><%=link_to "#{board.name}", board.name %></td>
          <td> Topicks: <%= board.topicks.size %>
          <br> Posts: <%= board.posts.size %></td>
          <td> Last post: <%= board.posts.last[:user_id] %></td>
        </tr>  
      <% end %> 
    </table>
  </div>
  <div id = "footer">
    <div class="outside">
      <h3>Forum info</h3>
      <div class="inside"></div>
    </div>
    <div class="outside">
      <h3>Forum statistics</h3>
      <div class="inside"></div>
    </div>
    <div class="outside">
      <h3>Forum population</h3>
      <div class="inside"></div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<%= stylesheet_link_tag "boards.scss" %>
<% @headerNeeded = true%>
<div id = "wrapper">
  <div id = "table_wrapper">
    <p><%= link_to "Create new board", 
      controller: "boards",
      action: "newBoard"%></p>
    <table id = "boards">
      <% @boards.reverse.each do |board| %>
        <tr>  
          <td><%=link_to "#{board.name}", board_path(board) %></td>
          <td> Topicks: <%= board.topicks.size %>
          <br> Posts: <%= board.posts.size %></td>
          <td> Last post: <%= board.posts.last.user.handle%>
          <br> On: <%= board.posts.last.updated_at %>
          </td>
        </tr>  
      <% end %> 
    </table>
  </div>
  <div id = "footer">
    <div class="outside">
      <h3>Forum info</h3>
      <div class="inside"></div>
    </div>
    <div class="outside">
      <h3>Forum statistics</h3>
      <div class="inside"></div>
    </div>
    <div class="outside">
      <h3>Forum population</h3>
      <div class="inside"></div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<%= stylesheet_link_tag "boards.scss" %>
<% @headerNeeded = true%>
<div id = "wrapper">
  <div id = "table_wrapper">
    <p><%= link_to "Start new topick", 
      controller: "topicks",
      action: "newTopick"%></p>
    <table id = "topicks">
      <% @topicks.each do |topick| %>
        <tr>  
          <td><%= link_to "#{topick.theme}", topick_path(topick)%></td>
          <td> Last post: <%= topick.posts.last.user.handle%>
          <br> On: <%= topick.posts.last.updated_at %>
          </td>
        </tr>  
      <% end %> 
    </table>
  </div>
  <div id = "footer">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if @headerNeeded %>
    <div id = "header">
      <% if current_user %>
        <h4>
        <%= current_user.handle %> <%= link_to "Log out", logout_path, method:  "delete" %>
        </h4>
      <% else %>
        <h5>
          Please, login or <%= link_to "register", '/register' %>.
        </h5>
        <%= form_for(:session, url: login_path) do |f| %>
          <%= f.email_field :email, placeholder: "Email" %>
          <%= f.password_field :password, placeholder: "password" %>
          <%= f.submit "Login", id: "btn-subm" %>
        <% end %> 
      <%end%>  
    </div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<%= stylesheet_link_tag "main.scss" %>
<div id = "wrapper">
  <div id = "header">
    <%= link_to "Login" %>
    <%= link_to "Register" %>
  </div>
  <div id = "table_wrapper">
    <p><%= link_to "Create new board", 
      controller: "main",
      action: "newBoard"%></p>
    <table id = "boards">
      <th>Board name</th>
      <th>Statistics</th>
      <th>Last posts</th>
      <% @boards.each do |board| %>
        <tr>  
          <td><%= link_to board.board_name %></td>
          <td> Topics: <%= board.topicks %>
          <br> Posts: <%= board.posts %></td>
          <td> Last post:<%= link_to board.last_poster %></td>
        </tr>  
      <% end %>  
    </table>
  </div>
  <div id = "footer">
    <div class="outside">
      <h3>Forum info</h3>
      <div class="inside"></div>
    </div>
    <div class="outside">
      <h3>Forum statistics</h3>
      <div class="inside"></div>
    </div>
    <div class="outside">
      <h3>Forum population</h3>
      <div class="inside"></div>
    </div>
  </div>
</div>

app/views/topicks/index.html.erb
<% @headerNeeded = true %>
<div id = "wrapper">
  <div id = "table_wrapper">
    <table id = "topicks">
      <% @posts.each do |post| %>
        <tr>  
          <td><h3><%= post.user.handle %></h3>
          <br> <%= image_path post.user.avatar %> 
          </td>
          <td> <h4><p><%= post.message %></p></h4>
          <br> <h5><p>Last redacted at: <%= post.updated_at %></p></h5>
          </td>
        </tr>  
      <% end %> 
    </table>
  </div>
  <div id = "footer">
  </div>
</div>

app/views/users/new.html.erb
<div id="wrapper">
  <div id="register_form">
    <%= form_for(@user) do |f|  %>
      <%= f.text_field :handle, placeholder: "Handle" %>
      <%= f.text_field :email, placeholder: "Email" %>
      <%= f.password_field :password, placeholder: "Password" %>
      <%= f.password_field :password_conformation, placeholder: "Repeat password" %>
      <%= f.submit "Creat an account", id: "btn-subm" %>
    <% end %>
  </div>
</div>